### ISSUE TITLE
pali text source

### ISSUE THREAD

**Issue by pathnirvana** [pndaza/tipitaka-pali#1]
No really an issue - but I would like to know what is the source of the text for this tipitaka pali app?
Was it obtained from the VRI vipassana research institute? tipitaka.org?

**Comment by pndaza** [comment]
I obtained most of books from CSP IOS App. But I think source of those text are from tipitaka.org. CSP IOS app developer added burmese published page-break marker. Some books are directly obtained from tipitaka.org. Saddanīti suttamālā ⁠are from someone. Another two books are from facebook. I think i need permission from VRI.

**Comment by pathnirvana** [comment]
Many thanks @pndaza Bhante for the information. Someone told me that there is another source of Chatta Sangithi text and that is why I was curious.
